<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Handsontable</name>
   <tag></tag>
   <elementGuidId>b858884c-5d1f-486f-bdae-cc96c976038c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.handsontable</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
